### ISSUE TITLE
The solution of "Reverse Words in a String" is not correct

### ISSUE THREAD

**Issue by tangweikun** [hanzichi/leetcode#12]
I think you misunderstand the leetcode description about this problem
That's my test case about this problem, maybe will help you to check your solution
[TestCase](https://github.com/tangweikun/leetcode/blob/9be82fa1079f360beb8222ddd556ce80ac1c6115/src/reverseWordsInAString3/test.ts)

**Comment by lessfish** [comment]
@tangweikun 

Hi, maybe what you are looking for is "Reverse Words in a String III" instead of "Reverse Words in a String"? [Here](https://github.com/hanzichi/leetcode/tree/master/Algorithms/Reverse%20Words%20in%20a%20String%20III) it is 

Btw, the first two test cases of yours are the same?

**Comment by tangweikun** [comment]
@hanzichi 
Sorry about that, what I mention about is [Reverse Words in a String III](https://github.com/hanzichi/leetcode/tree/master/Algorithms/Reverse%20Words%20in%20a%20String%20III)
Btw, thanks for point out my duplication test case, I already remove it.
