### ISSUE TITLE
关于readme.md的 update

### ISSUE THREAD

**Issue by monster-wang-aws** [hanzichi/leetcode#3]
你好，从博客园一路逛过来看的。感觉 leetcode 上能拿 js 刷了这么多题的人真不多见😂，我之前也是用 JS， 后来还是随大流用了 Java

主要想问下你 readme.md 是写了什么脚本更新吗？方便就此交流一下吗？
谢谢

**Comment by lessfish** [comment]
@monster-gump 方便呀~ 用的 Node.js
