### ISSUE TITLE
试了下你的 generate.js 爬出貌似失效了

### ISSUE THREAD

**Issue by KMBaby-zyl** [hanzichi/leetcode#4]
$('#problemList tbody tr') 是空

去网站上搜 problemList 也没有。

是leetcode更新了页面dom，还是我打开方式不对 :-(

**Comment by KMBaby-zyl** [comment]
leetcode改成接口了 更方便了～～

**Comment by lessfish** [comment]
@KMBaby-zyl 对的，改成接口形式了，generate.js 文件更新不再显示了，如果有需要的话我可以更下
