### ISSUE TITLE
Add Two Numbers这个算法有什么用啊？

### ISSUE THREAD

**Issue by catchOneW** [hanzichi/leetcode#9]
看样子就是把链表的每一个数字加起来，如果超过10就取余数，进的一个1就参与到后面2个数的相加里去，最后得出一个新的链表，这样做的意义是什么？哪些实际问题是需要这种算法的？

**Comment by lessfish** [comment]
我个人觉得，准确地说，可能这并不是一个算法，只是为了训练你的 **逻辑思维能力**。

同样，leetcode 上很多题我觉得并不是算法题。
